INSERT INTO 
    "Category" ("CategoryName","user_id")
VALUES
    ('Accounting and Finance',19),
    ('Admin, Secretarial and Clerical',20),
    ('Advertising and Media',20),
    ('Agriculture',20),
    ('Architecture and Construction',20),
    ('Automotive',19),
    ('Banking and Insurance',20),
    ('Business Development',20),
    ('Business and Administration',19),
    ('Civil Service and Government',20),
    ('Communications, PR and Journalism ',20),
    ('Community Service',19),
    ('Consultancy and Training',20),
    ('Creative Arts',19),
    ('Customer Service',20),
    ('Development and Project Management',20),
    ('Economics',19),
    ('Education',19),
    ('Engineering',19),
    ('Entertainment',19),
    ('Environment and Natural Resource',19),
    ('Event Management',19),
    ('Health Care',20),
    ('Hotel and Hospitality',19),
    ('Human Resource and Recruitment ',20),
    ('Information Technology',19),
    ('Inventory and Stock',19),
    ('Languages',20),
    ('Legal',19),
    ('Logistics, Transport and Supply Chain ',20),
    ('Maintenance',20),
    ('Management',19),
    ('Manufacturing',19),
    ('Media and Journalism',20),
    ('Natural Sciences',20),
    ('Pharmaceutical',19),
    ('Purchasing and Procurement',20),
    ('Quality Assurance',19),
    ('Research and Development',19),
    ('Retail, Wholesale and Distribution',20),
    ('Sales and Marketing',19),
    ('Science and Technology',19)
RETURNING *;

